### ISSUE TITLE
حذف یا درج منبع کد ها

### ISSUE THREAD

**Issue by javad-zobeidi** [resfandiari/cafebazaar_market#1]
با سلام و عرض ادب

درخصوص این پکیج که شما منتشر کردید دارید از کد های پکیج های کافه بازار
 (https://pub.dev/packages/cafebazaar_flutter)
 به صورت کامل استفاده  میکنید یا منبع کد ها رو در داکیومنت پکیج خود درج میکنید یا بل کل پکیج رو دیپریکیت کنید در غییر این صورت ایمیل به تیم مدیریتی pub.dev ارسال میشود

**Comment by resfandiari** [comment]
سلام و درود

قبلا در مقاله موجود در سایت ویرگول توضیح کامل دادم در مورد پکیج شما و چرایی نوشتن پکیج جدید
لینک مقاله:
https://bit.ly/2BDGUMU

 نام با پکیج شما در داکیومنت قید شد. با تشکر

**Comment by javad-zobeidi** [comment]
توی دنیای برنامه نویسی و دنیای  برنامه های متن باز معمولا اگر برنامه ای نوشته شد و متن باز منتشر شد و برنامه مشکلی یا باگی داشته باشه برنامه نویس های دیگه بجای این که بیان تمامی کد های اون پکیج رو کپی کنند دقیقا همون کد ها رو کپی کنند فقط باگ رو رفع کنند بعد به اسم خودشون منتشر کنند اون برنامه رو به اصطلاح fork میکنند و باگ رو رفع میکنند و  یک درخواست به سازنده میدن که کد های جدید رفع شده رو بر روی برنامه ادغام کنه  اگر برنامه نویس  دیگه بیاد کد ها رو کپی کنه  و به اسمش بزنه حق برنامه نویس اصلی رو ضایع کرده

**Comment by resfandiari** [comment]
> توی دنیای برنامه نویسی و دنیای برنامه های متن باز معمولا اگر برنامه ای نوشته شد و متن باز منتشر شد و برنامه مشکلی یا باگی داشته باشه برنامه نویس های دیگه بجای این که بیان تمامی کد های اون پکیج رو کپی کنند دقیقا همون کد ها رو کپی کنند فقط باگ رو رفع کنند بعد به اسم خودشون منتشر کنند اون برنامه رو به اصطلاح fork میکنند و باگ رو رفع میکنند و یک درخواست به سازنده میدن که کد های جدید رفع شده رو بر روی برنامه ادغام کنه اگر برنامه نویس دیگه بیاد کد ها رو کپی کنه و به اسمش بزنه حق برنامه نویس اصلی رو ضایع کرده

**Comment by resfandiari** [comment]
سلام و درود
بله شما درست می فرمایید اما این برای زمانی هست که یک ویژگی جدید به پکیج اظافه بشه یا یک باگ رفع بشه نه اینکه پکیج از بیس قرار باشه عوض بشه همینجور که گفتم در مطلب پکیج شما علاوه بر چند مورد باگ طبق ریلیز قبلی هم بود که همین باعث میشد همه چی تغییر کنه .
در ضمن کدهایی که میفرمایید کپی شده اگر منظورتون کدهای بخش پرداخت هست اینها کدهای موجود در وب سایت بازار است و شما مالکیتی روی اون ندارید.
در ضمن اسم پکیج شما هم در داکیومنت ثبت شده.
موفق باشید.
