### ISSUE TITLE
Problem setting up In-app Billing

### ISSUE THREAD

**Issue by Rezayzdni** [resfandiari/cafebazaar_market#2]
hi , while i was using the plugin cafebazzar_market i faced the following error :
`Problem setting up In-app Billing: IabResult: Billing service unavailable on device. (response: 3:Billing Unavailable)
E/CafebazaarPaymentService( 3518): Reply already submitted
W/System.err( 3518): java.lang.NullPointerException: Attempt to invoke interface method 'long com.farsitel.bazaar.IUpdateCheckService.getVersionCode(java.lang.String)' on a null object reference
W/System.err( 3518): 	at com.resfandiari.cafebazaar_market.CafebazaarUpdateService.doCheck(CafebazaarUpdateService.java:66)
W/System.err( 3518): 	at com.resfandiari.cafebazaar_market.CafebazaarUpdateService.access$000(CafebazaarUpdateService.java:23)
W/System.err( 3518): 	at com.resfandiari.cafebazaar_market.CafebazaarUpdateService$1.run(CafebazaarUpdateService.java:57)
W/System.err( 3518): 	at android.os.Handler.handleCallback(Handler.java:739)
W/System.err( 3518): 	at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err( 3518): 	at android.os.Looper.loop(Looper.java:135)
W/System.err( 3518): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
W/System.err( 3518): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 3518): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 3518): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
W/System.err( 3518): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)`

which is kind of platform exception ..
why is that happening and how can i fix it.
thanks a lot!

**Comment by resfandiari** [comment]
hi , thanks for using this package 
I can't help you without having much information.So instead I'll try to do a checklist for you in case you missed something:

1.Are you testing on an emulator?Billing services should be tested on devices,BUT if you really have to test on the emulator,make sure the emulator has Cafe Bazaar installed and set up.This is very important!

2.If you are still testing the app,did you get a test app licence from the Cafe Bazaar, imported the level in your SDK ,set up your licence verification library? (you can follow along here: https://pub.dev/packages/cafebazaar_market#cafe-bazaar-payment )

3. please run example app of this library on your system and check the problem
https://github.com/resfandiari/cafebazaar_market/tree/master/example

If you still have problems, please send output of this code here:
```
flutter doctor -v
```
Regards

**Comment by Rezayzdni** [comment]
problem solved by installing cafe bazaar app on my device .
thanks a lot!
