### ISSUE TITLE
Invalid key specification

### ISSUE THREAD

**Issue by Rezayzdni** [resfandiari/cafebazaar_market#3]
hi , i started the purchase flow and redirected to payment bank page and pay the specified price and payment was successful 
after that i hit the "انتقال به سایت پذیرنده"  bazzar said the payment was successful but i got the following error and i could'nt 
configure successful payment in my app :
`
Invalid key specification.
D/AndroidRuntime(15330): Shutting down VM
E/AndroidRuntime(15330): FATAL EXCEPTION: main
E/AndroidRuntime(15330): Process: jico.behyad.workar, PID: 15330
E/AndroidRuntime(15330): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=10001, result=-1, data=Intent { (has extras) }} to activity {jico.behyad.workar/jico.behyad.workar.MainActivity}: java.lang.IllegalArgumentException: java.security.spec.InvalidKeySpecException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: Error parsing public key
E/AndroidRuntime(15330): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4729)
E/AndroidRuntime(15330): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4771)
E/AndroidRuntime(15330): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime(15330): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(15330): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(15330): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1993)
E/AndroidRuntime(15330): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(15330): 	at android.os.Looper.loop(Looper.java:216)
E/AndroidRuntime(15330): 	at android.app.ActivityThread.main(ActivityThread.java:7285)
E/AndroidRuntime(15330): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15330): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/AndroidRuntime(15330): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
E/AndroidRuntime(15330): Caused by: java.lang.IllegalArgumentException: java.security.spec.InvalidKeySpecException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: Error parsing public key
E/AndroidRuntime(15330): 	at com.resfandiari.cafebazaar_market.util.Security.generatePublicKey(Security.java:85)
E/AndroidRuntime(15330): 	at com.resfandiari.cafebazaar_market.util.Security.verifyPurchase(Security.java:65)
E/AndroidRuntime(15330): 	at com.resfandiari.cafebazaar_market.util.IabHelper.handleActivityResult(IabHelper.java:543)
E/AndroidRuntime(15330): 	at com.resfandiari.cafebazaar_market.CafebazaarPaymentService.activityResult(CafebazaarPaymentService.java:209)
E/AndroidRuntime(15330): 	at com.resfandiari.cafebazaar_market.MethodCallHandlerImpl.onActivityResult(MethodCallHandlerImpl.java:171)
E/AndroidRuntime(15330): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
E/AndroidRuntime(15330): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime(15330): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:597)
E/AndroidRuntime(15330): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:582)
E/AndroidRuntime(15330): 	at android.app.Activity.dispatchActivityResult(Activity.java:7811)
E/AndroidRuntime(15330): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4722)
E/AndroidRuntime(15330): 	... 11 more
E/AndroidRuntime(15330): Caused by: java.security.spec.InvalidKeySpecException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: Error parsing public key
E/AndroidRuntime(15330): 	at com.android.org.conscrypt.OpenSSLKey.getPublicKey(OpenSSLKey.java:296)
E/AndroidRuntime(15330): 	at com.android.org.conscrypt.OpenSSLRSAKeyFactory.engineGeneratePublic(OpenSSLRSAKeyFactory.java:54)
E/AndroidRuntime(15330): 	at java.security.KeyFactory.generatePublic(KeyFactory.java:361)
E/AndroidRuntime(15330): 	at com.resfandiari.cafebazaar_market.util.Security.generatePublicKey(Security.java:80)
E/AndroidRuntime(15330): 	... 21 more
E/AndroidRuntime(15330): Caused by: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: Error parsing public key
E/AndroidRuntime(15330): 	at com.android.org.conscrypt.NativeCrypto.EVP_parse_public_key(Native Method)
E/AndroidRuntime(15330): 	at com.android.org.conscrypt.OpenSSLKey.getPublicKey(OpenSSLKey.java:294)
E/AndroidRuntime(15330): 	... 24 more
`

**Comment by resfandiari** [comment]
please send the output of this code here:
```
flutter doctor -v
```
Regards

**Comment by Rezayzdni** [comment]
here is the output : 

`[√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.18362.778], locale en-US)
    • Flutter version 1.18.0-11.1.pre at E:\sdk\flutter sdk beta\flutter
    • Framework revision 2738a1148b (3 months ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at E:\sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = E:\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at E:\IntelliJ IDEA Community Edition 2019.3.4
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361

[√] Connected device (1 available)
    • Google Nexus 4 1 API 21 • 192.168.166.102:5555 • android-x86 • Android 5.0 (API 21)

• No issues found!
`

**Comment by Rezayzdni** [comment]
سلام آقای اسفندیاری وقتتون به خیر .
مشکل حل نشد؟ آخه میدونید الان پروژم  فقط درگاهش مونده و کارفرما منتظر هست و
وقت زیادی برام نمونده .
با سپاس فراوان از زحمات شما .

‫‪Reza Esfandiari‬‏ <‪notifications@github.com‬‏> در تاریخ چهارشنبه ۲۹
ژوئیهٔ ۲۰۲۰ ساعت ۱۰:۵۲ نوشت:‬

**Comment by resfandiari** [comment]
سلام و درود

پوزش بابت تاخیر.متاسفانه به دلیل مشغله کاری فعلا قادر به رفع مشکل نیستم ولی
با توجه به تست های انجام شده پکیج
روی کانال stable فاقد مشکل هست برای خروجی از این کانال استفاده کنید.

موفق باشید
رضا اسفندیاری

**Comment by Rezayzdni** [comment]
این کارو هم کردم ولی بازم مشکل حل نشد

**Comment by resfandiari** [comment]
درود.
چه عملیاتی میخواید  انجام بدید؟

**Comment by Rezayzdni** [comment]
من اپی دارم که از پرداخت درون برنامه ای از نوع غیر مصرفی استفاده میکنه . وقت که اقدام به خرید میکنم و بعد از موفقیت آمیز بودن خرید و ظاهر شدن پیام پرداخت موفقیت آمیز بودن پرداخت روی صفحه گوشی در بکند و در کدم با خطای عدم دریافت اطلاعات پرداخت از سوی سرور بازار مواجه میشم .



با اینکه پرداخت انجام شده و بازار هم تایید کرده اما در کد برنامه انگار پرداختی انجام نشده ونمیشه بخش پولی برنامم رو برای کاربر باز کنم و وقتی خرید مجدد هم میزنم پیام قبلا خریداری شده برام ظاهر میشه .

قطعه کدهایی که در برنامه استفاده کردم  :

این تابع رو تو initState صدا میزنم تا وصل شه به کافه بازار:

`Future initConnectToBazaar() async {

try {

bool connect = await CafebazaarFlutter.initPay(rsaKey: 'xxxxxxx',debugMode: true);

if (connect) {

print('connected');

} else {

print('خطا در ارتباط با سرور!');

}

} on PlatformException {

print('لطفا مطمئن بشید که کافه بازار رو نصب دارین.');

}

if (!mounted) return;

}`


این هم که درخواست خرید میده و نتایج از سمت بازار رو میده:

`Map result =await CafebazaarFlutter.launchPurchaseFlow(sku: "Jico",consumption: false,payload:"bReZz+V7g/yqDXvKRqq+JTFn4uQZbPiQJo4pf9RzJ");

Map result2 = await CafebazaarFlutter.getPurchase(sku:"Jico");

bool isVerified = await CafebazaarFlutter.verifyDeveloperPayload(payload: "bReZz+V7g/yqDXvKRqq+JTFn4uQZbPiQJo4pf9RzJ");`

**Comment by Rezayzdni** [comment]
issue solved . RSA key was incorrect.
