### ISSUE TITLE
IAB helper is not set up

### ISSUE THREAD

**Issue by Rezayzdni** [resfandiari/cafebazaar_market#5]
greatings.
some times when i want to launch purchase flow with caffe bazaar i have to try about 4 or 5 times clicking on launch purchase flow 
to execute this line : `bool connect = await CafebazaarMarket.initPay(rsaKey: xxxxxx);`
untill its start to setup IAB helper and when its not ready to set up i cant catch the not ready state state. what should i do?
and also here is the error message :
`D/CafebazaarPaymentService( 5020): Starting setup.
D/CafebazaarPaymentService( 5020): launchPurchaseFlow
E/IabHelper( 5020): In-app billing error: Illegal state for operation (launchPurchaseFlow): IAB helper is not set up.
E/MethodCallHandlerImpl( 5020): IAB helper is not set up. Can't perform operation: launchPurchaseFlow
D/CafebazaarPaymentService( 5020): Setup finished.`

i'll be glad if someone help me .

**Comment by resfandiari** [comment]
hi,
you should config **initPay** method by **FutureBuilder** like this :
 
```dart
class PaymentPage extends StatefulWidget {
  @override
  _PaymentPageState createState() => _PaymentPageState();
}

class _PaymentPageState extends State<PaymentPage> {
  @override
  void initState() {
    super.initState();
  }

  // Platform messages are asynchronous, so we initialize in an async method.
  Future<bool> initPlatformState() async {
    // Platform messages may fail, so we use a try/catch PlatformException.
    bool result = await CafebazaarMarket.initPay(rsaKey: Consts.BAZAR_KEY);
    print("_CafebazaarMarket connected for payment $result");

    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return false;

    return result;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: FutureBuilder<bool>(
        future: initPlatformState(),
        builder: (BuildContext context, AsyncSnapshot<bool> snapshot) {
          List<Widget> children;
          if (snapshot.hasData) {
            children = <Widget>[
              Icon(
                Icons.check_circle_outline,
                color: Colors.green,
                size: 60,
              ),
              Padding(
                padding: const EdgeInsets.only(top: 16),
                child: Text('Result: Successful connection to cafe bazaar'),
              )
            ];
          } else if (snapshot.hasError) {
            children = <Widget>[
              Icon(
                Icons.error_outline,
                color: Colors.red,
                size: 60,
              ),
              Padding(
                padding: const EdgeInsets.only(top: 16),
                child: Text(
                    AppLocalizations.of(context).translate("not_find_bazar")),
              )
            ];
          } else {
            children = <Widget>[
              SizedBox(
                child: CircularProgressIndicator(),
                width: 60,
                height: 60,
              ),
              Padding(
                padding: EdgeInsets.only(top: 16),
                child:
                    Text(AppLocalizations.of(context).translate("please_wait")),
              )
            ];
          }
          return Center(
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: children,
              ),
            ),
          );
        },
      ),
    );
  }

  @override
  void dispose() {
    CafebazaarMarket.disposePayment();
    super.dispose();
  }
}

```

and show your payment widget when **snapshot.hasData**

**Comment by Rezayzdni** [comment]
now it's getting even worse !!
when snapshot has data i call this method: `await CafebazaarMarket.launchPurchaseFlow(
        sku: "xx",
        consumption: false,
        payload:
        'xx');`
i get following error in debug console :
`In-app billing error: Null data in IAB activity result.
D/CafebazaarPaymentService(27467): Error purchasing: IabResult: Null data in IAB result (response: -1002:Bad response received)`
and  'محصول وجود ندارد' message  from bazaar server .

**Comment by Rezayzdni** [comment]
> now it's getting even worse !!
> when snapshot has data i call this method: `await CafebazaarMarket.launchPurchaseFlow( sku: "xx", consumption: false, payload: 'xx');`
> i get following error in debug console :
> `In-app billing error: Null data in IAB activity result. D/CafebazaarPaymentService(27467): Error purchasing: IabResult: Null data in IAB result (response: -1002:Bad response received)`
> and 'محصول وجود ندارد' message from bazaar server .

my bad! package name was not set.
 your code works fine but i have a another question to ask
how do you cover **platform exception** in your code?
thanks a lot.

**Comment by Rezayzdni** [comment]
oh , realized that platform exception has been covered in **snapShot.hasError** , thanks anyway.
so i guess im gonna close this issue.
